a = {}
n1 = input("Enter name 1: ")
n2 = input("Enter name 2: ")
n3 = input("Enter name 3: ")
n4 = input("Enter name 4: ")
l1 = input("Enter fav lang for "+n1+": ")
l2 = input("Enter fav lang for "+n2+": ")
l4 = input("Enter fav lang for "+n4+": ")
l3 = input("Enter fav lang for "+n3+": ")
a.update({n1:l1})
a.update({n2:l2})
a.update({n3:l3})
a.update({n4:l4})
print(a)